In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df = pd.read_csv("/content/Phising_Detection_Dataset.csv")

In [36]:
df

,Unnamed: 0,NumDots,UrlLength,NumDash,AtSymbol,IpAddress,HttpsInHostname,PathLevel,PathLength,NumNumericChars,Phising
0,0,3,72,0,0,0,0,5,44,0,1.0
1,1,3,144,0,0,0,0,3,16,41,1.0
2,2,3,58,0,0,0,0,2,24,0,1.0
3,3,3,79,1,0,0,0,6,50,0,1.0
4,4,3,46,0,0,0,0,4,29,2,1.0
...,...,...,...,...,...,...,...,...,...,...,...
662586,662586,3,39,0,0,0,0,4,39,1,1.0
662587,662587,2,44,2,0,0,0,4,44,1,1.0
662588,662588,2,42,0,0,0,0,4,42,1,1.0
662589,662589,2,45,0,0,0,0,3,45,0,1.0
662590,662590,2,41,0,0,0,0,3,41,0,1.0

In [37]:
df = df.drop('Unnamed: 0',axis=1)
df

,NumDots,UrlLength,NumDash,AtSymbol,IpAddress,HttpsInHostname,PathLevel,PathLength,NumNumericChars,Phising
0,3,72,0,0,0,0,5,44,0,1.0
1,3,144,0,0,0,0,3,16,41,1.0
2,3,58,0,0,0,0,2,24,0,1.0
3,3,79,1,0,0,0,6,50,0,1.0
4,3,46,0,0,0,0,4,29,2,1.0
...,...,...,...,...,...,...,...,...,...,...
662586,3,39,0,0,0,0,4,39,1,1.0
662587,2,44,2,0,0,0,4,44,1,1.0
662588,2,42,0,0,0,0,4,42,1,1.0
662589,2,45,0,0,0,0,3,45,0,1.0
662590,2,41,0,0,0,0,3,41,0,1.0

In [38]:
df.head()

,NumDots,UrlLength,NumDash,AtSymbol,IpAddress,HttpsInHostname,PathLevel,PathLength,NumNumericChars,Phising
0,3,72,0,0,0,0,5,44,0,1.0
1,3,144,0,0,0,0,3,16,41,1.0
2,3,58,0,0,0,0,2,24,0,1.0
3,3,79,1,0,0,0,6,50,0,1.0
4,3,46,0,0,0,0,4,29,2,1.0

In [39]:
df.shape

(662591, 10)

In [40]:
df.columns

Index(['NumDots', 'UrlLength', 'NumDash', 'AtSymbol', 'IpAddress',
       'HttpsInHostname', 'PathLevel', 'PathLength', 'NumNumericChars',
       'Phising'],
      dtype='object')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 662591 entries, 0 to 662590
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   NumDots          662591 non-null  int64
 1   UrlLength        662591 non-null  int64
 2   NumDash          662591 non-null  int64
 3   AtSymbol         662591 non-null  int64
 4   IpAddress        662591 non-null  int64
 5   HttpsInHostname  662591 non-null  int64
 6   PathLevel        662591 non-null  int64
 7   PathLength       662591 non-null  int64
 8   NumNumericChars  662591 non-null  int64
 9   Phising          630071 non-null  float64
dtypes: float64(1), int64(9)
memory usage: 50.6 MB

In [42]:
df.describe()

,NumDots,UrlLength,NumDash,AtSymbol,IpAddress,HttpsInHostname,PathLevel,PathLength,NumNumericChars,Phising
count,662591.000000,662591.000000,662591.000000,662591.000000,662591.000000,662591.000000,662591.000000,662591.000000,662591.000000,630071.000000
mean,2.195062,60.254036,1.551831,0.002185,0.011283,0.025989,2.791045,40.996062,0.652540,0.158730
std,1.490275,44.597468,2.973611,0.053758,0.105620,0.162509,1.625727,29.722431,1.429861,0.365424
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,32.000000,0.000000,0.000000,0.000000,0.000000,2.000000,21.000000,0.000000,0.000000
50%,2.000000,48.000000,0.000000,0.000000,0.000000,0.000000,3.000000,35.000000,1.000000,0.000000
75%,3.000000,77.000000,2.000000,0.000000,0.000000,0.000000,4.000000,53.000000,1.000000,0.000000
max,42.000000,2175.000000,87.000000,10.000000,1.000000,5.000000,38.000000,2175.000000,111.000000,1.000000

In [43]:
df.isnull().sum()

NumDots                0
UrlLength              0
NumDash                0
AtSymbol               0
IpAddress              0
HttpsInHostname        0
PathLevel              0
PathLength             0
NumNumericChars        0
Phising            32520
dtype: int64

In [44]:
df.fillna(df.median(numeric_only=True), inplace=True)
df

,NumDots,UrlLength,NumDash,AtSymbol,IpAddress,HttpsInHostname,PathLevel,PathLength,NumNumericChars,Phising
0,3,72,0,0,0,0,5,44,0,1.0
1,3,144,0,0,0,0,3,16,41,1.0
2,3,58,0,0,0,0,2,24,0,1.0
3,3,79,1,0,0,0,6,50,0,1.0
4,3,46,0,0,0,0,4,29,2,1.0
...,...,...,...,...,...,...,...,...,...,...
662586,3,39,0,0,0,0,4,39,1,1.0
662587,2,44,2,0,0,0,4,44,1,1.0
662588,2,42,0,0,0,0,4,42,1,1.0
662589,2,45,0,0,0,0,3,45,0,1.0
662590,2,41,0,0,0,0,3,41,0,1.0

In [45]:
df['Phising'].value_counts(dropna=False)

Phising
0.0    562580
1.0    100011
Name: count, dtype: int64

In [46]:
df['Phising'].isnull().sum()

np.int64(0)

In [47]:
df = df.dropna(subset=['Phising'])
df

,NumDots,UrlLength,NumDash,AtSymbol,IpAddress,HttpsInHostname,PathLevel,PathLength,NumNumericChars,Phising
0,3,72,0,0,0,0,5,44,0,1.0
1,3,144,0,0,0,0,3,16,41,1.0
2,3,58,0,0,0,0,2,24,0,1.0
3,3,79,1,0,0,0,6,50,0,1.0
4,3,46,0,0,0,0,4,29,2,1.0
...,...,...,...,...,...,...,...,...,...,...
662586,3,39,0,0,0,0,4,39,1,1.0
662587,2,44,2,0,0,0,4,44,1,1.0
662588,2,42,0,0,0,0,4,42,1,1.0
662589,2,45,0,0,0,0,3,45,0,1.0
662590,2,41,0,0,0,0,3,41,0,1.0

In [48]:
X = df.drop('Phising', axis=1)
y = df['Phising']

In [49]:
X

,NumDots,UrlLength,NumDash,AtSymbol,IpAddress,HttpsInHostname,PathLevel,PathLength,NumNumericChars
0,3,72,0,0,0,0,5,44,0
1,3,144,0,0,0,0,3,16,41
2,3,58,0,0,0,0,2,24,0
3,3,79,1,0,0,0,6,50,0
4,3,46,0,0,0,0,4,29,2
...,...,...,...,...,...,...,...,...,...
662586,3,39,0,0,0,0,4,39,1
662587,2,44,2,0,0,0,4,44,1
662588,2,42,0,0,0,0,4,42,1
662589,2,45,0,0,0,0,3,45,0
662590,2,41,0,0,0,0,3,41,0

In [50]:
y

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ...
662586    1.0
662587    1.0
662588    1.0
662589    1.0
662590    1.0
Name: Phising, Length: 662591, dtype: float64

In [52]:
print(df['Phising'].value_counts())

Phising
0.0    562580
1.0    100011
Name: count, dtype: int64

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [60]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    class_weight='balanced',
    random_state=42
)
model.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10, random_state=42)

In [61]:
y_pred = model.predict(X_test)

In [62]:
y_pred

array([0., 0., 1., ..., 0., 0., 1.])

In [64]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7878794738867634

In [65]:
print(df['Phising'].unique())

[1. 0.]

In [66]:
import joblib

joblib.dump(model, "model.pkl",compress=3)

['model.pkl']

In [68]:
from google.colab import files

files.download("model.pkl")

In [69]:
print(X.columns)

Index(['NumDots', 'UrlLength', 'NumDash', 'AtSymbol', 'IpAddress',
       'HttpsInHostname', 'PathLevel', 'PathLength', 'NumNumericChars'],
      dtype='object')